#!/usr/bin/env bash

DEFAULT_GUEST_COMPONENTS_REPOSITORY="https://github.com/confidential-containers/guest-components"
DEFAULT_GUEST_COMPONENTS_REF="v0.18.0"
DEFAULT_PAUSE_IMAGE_REPOSITORY="docker://registry.k8s.io/pause"
DEFAULT_PAUSE_IMAGE_VERSION="3.10"
DEFAULT_RESOLV_CONF_NAMESERVER="8.8.8.8"

GUEST_COMPONENTS_REPOSITORY="${GUEST_COMPONENTS_REPOSITORY:-${DEFAULT_GUEST_COMPONENTS_REPOSITORY}}"
GUEST_COMPONENTS_REF="${GUEST_COMPONENTS_REF:-${DEFAULT_GUEST_COMPONENTS_REF}}"
PAUSE_IMAGE_REPOSITORY="${PAUSE_IMAGE_REPOSITORY:-${DEFAULT_PAUSE_IMAGE_REPOSITORY}}"
PAUSE_IMAGE_VERSION="${PAUSE_IMAGE_VERSION:-${DEFAULT_PAUSE_IMAGE_VERSION}}"
RESOLV_CONF_NAMESERVER="${RESOLV_CONF_NAMESERVER:-${DEFAULT_RESOLV_CONF_NAMESERVER}}"
