#!/usr/bin/env bash

# Keep Kata inputs here so changes trigger the CI initrd and rootfs image rebuild.
DEFAULT_KATA_RELEASE_REPOSITORY="asterinas/kata-containers"
DEFAULT_KATA_VERSION="3.28.0-20260906"
DEFAULT_GUEST_COMPONENTS_REPOSITORY="https://github.com/confidential-containers/guest-components"
DEFAULT_GUEST_COMPONENTS_REF="v0.18.0"
DEFAULT_PAUSE_IMAGE_REPOSITORY="docker://registry.k8s.io/pause"
DEFAULT_PAUSE_IMAGE_VERSION="3.10"
DEFAULT_RESOLV_CONF_NAMESERVER="8.8.8.8"

KATA_VERSION="${KATA_VERSION:-${DEFAULT_KATA_VERSION}}"
KATA_RELEASE_REPOSITORY="${KATA_RELEASE_REPOSITORY:-${DEFAULT_KATA_RELEASE_REPOSITORY}}"
KATA_RELEASE_TAG="${KATA_RELEASE_TAG:-${KATA_VERSION}-asterinas}"
GUEST_COMPONENTS_REPOSITORY="${GUEST_COMPONENTS_REPOSITORY:-${DEFAULT_GUEST_COMPONENTS_REPOSITORY}}"
GUEST_COMPONENTS_REF="${GUEST_COMPONENTS_REF:-${DEFAULT_GUEST_COMPONENTS_REF}}"
PAUSE_IMAGE_REPOSITORY="${PAUSE_IMAGE_REPOSITORY:-${DEFAULT_PAUSE_IMAGE_REPOSITORY}}"
PAUSE_IMAGE_VERSION="${PAUSE_IMAGE_VERSION:-${DEFAULT_PAUSE_IMAGE_VERSION}}"
RESOLV_CONF_NAMESERVER="${RESOLV_CONF_NAMESERVER:-${DEFAULT_RESOLV_CONF_NAMESERVER}}"
