apiVersion: v1
kind: Pod
metadata:
  name: ollama-kata-qemu-tdx
spec:
  runtimeClassName: kata-qemu-tdx-asterinas
  containers:
    - name: ollama
      image: asterinas/ollama-cpu:openclaw-qwen2.5-0.5b
      imagePullPolicy: Always
      command: ["/usr/local/bin/pause"]
